# Generated by Django 3.1.1 on 2021-06-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='login',
        ),
        migrations.AlterModelTable(
            name='sign',
            table='sign',
        ),
    ]
